# Generated by Django 5.0.1 on 2024-01-10 12:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil_image',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numeracion', models.IntegerField()),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('id_provincia', models.CharField(choices=[('Buenos Aires', 'Buenos Aires'), ('Ciudad Autónoma de Buenos Aires', 'Ciudad Autónoma de Buenos Aires'), ('Catamarca', 'Catamarca'), ('Chaco', 'Chaco'), ('Chubut', 'Chubut'), ('Córdoba', 'Córdoba'), ('Corrientes', 'Corrientes'), ('Entre Ríos', 'Entre Ríos'), ('Formosa', 'Formosa'), ('Jujuy', 'Jujuy'), ('La Pampa', 'La Pampa'), ('La Rioja', 'La Rioja'), ('Mendoza', 'Mendoza'), ('Misiones', 'Misiones'), ('Neuquén', 'Neuquén'), ('Río Negro', 'Río Negro'), ('Salta', 'Salta'), ('San Juan', 'San Juan'), ('San Luis', 'San Luis'), ('Santa Cruz', 'Santa Cruz'), ('Santa Fe', 'Santa Fe'), ('Santiago del Estero', 'Santiago del Estero'), ('Tierra del Fuego, Antártida e Islas del Atlántico Sur', 'Tierra del Fuego, Antártida e Islas del (Atlántico Sur'), ('Tucumán', 'Tucumán')], default='X', max_length=100)),
                ('id_departamento', models.CharField(choices=[('Mendoza', [('Ciudad', 'Ciudad'), ('Maipu', 'Maipu'), ('Lujan', 'Lujan'), ('Las Heras', 'Las Heras'), ('Godoy Cruz', 'Godoy Cruz')]), ('Buenos Aires', [('Ciudad', 'Ciudad'), ('Maipu', 'Maipu'), ('Lujan', 'Lujan'), ('Las Heras', 'Las Heras'), ('Godoy Cruz', 'Godoy Cruz')])], default='X', max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_matricula', models.IntegerField(verbose_name='Número de matricula')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('id_especialidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='plataforma.especialidad', verbose_name='Especialidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_afiliado', models.BigIntegerField(blank=True, null=True)),
                ('apoderado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plataforma.paciente')),
                ('id_obra_social', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='plataforma.obrasocial', verbose_name='Obra Social')),
                ('medicos', models.ManyToManyField(blank=True, to='plataforma.medico', verbose_name='Médico con quien se atiende')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='pacientes',
            field=models.ManyToManyField(to='plataforma.paciente', verbose_name='Pacientes que atiende'),
        ),
    ]
